### ISSUE TITLE
[request] Increase the 79 character line length limit 

### ISSUE THREAD

**Issue by a-dubs** [canonical/pycloudlib#390]
Pweaaaseee can we increase the max line length to 120 chars. I'm begging dawg.

I value more verbose and informative variable names but this makes dealing with 79 chars max width impossible, especially after a few indents :sob: 

I'm willing to bargain. Even 100 would be a night and day difference vs 79. Heck, I'll work in exchange for having my needs met. Just say the word. I'll tattoo pycloudlib on my left thigh if I have to. Let's make it happen, guys, girls, and enbies. 

Thanks for hearing me out :P

**Comment by TheRealFalcon** [comment]
> I value more verbose and informative variable names but this makes dealing with 79 chars max width impossible

How long we talking? Install ruff into your editor and it should "just work" and automatically reformat things for most of these issues unless you want like 50+ character names, but I'd think those should be fairly rare. You just have to get used to more vertical space rather than horizontal.

That said, I don't personally have a problem increasing it, but we'll want to make sure others are on board. It'll be an ugly commit due to auto-reformatting so many lines, but `.git-blame-ignore-revs` should help with that somewhat. I asked about doing the same in this repo and in cloud-init a couple years back, and the main reasons I got for current values are:
1. pep8 default
2. If you have to edit code in a serial console (which is your only option if you have no network in a cloud instance), 80 chars is still your max-width there.
3. A previous maintainer liked being able to have 4 code columns side-by-side.

The serial console issue could still be relevant, but I don't see it as a large blocker, so count me as +1.

**Comment by a-dubs** [comment]
> A previous maintainer liked being able to have 4 code columns side-by-side.

Haha honestly I completely get that, and for that reason too, I'd be happy to just set line length to 100 instead of 120

**Comment by aciba90** [comment]
+1, thanks for rising this up!

**Comment by a-dubs** [comment]
100 it is!
