### ISSUE TITLE
feature: ec2 should provide a delete_keys operation

### ISSUE THREAD

**Issue by blackboxsw** [canonical/pycloudlib#431]
A delete_keys operation would be useful in cloud teardown when upload_keys is performed by intrgration tests in
tests/integration_tests/test_public_api.py.

**Comment by a-dubs** [comment]
after further investigation, i think i can close this ticket because:
A) ec2 already provides a delete_key() function 
B) it is already automatically called in the cleanup function

The reason the key was not being cleaned up in the error we see in #428 is because the key is created at the cloud level and the cloud gets re-used between tests. So once tests have completed, then the key gets auto cleaned up successfully.

**Comment by blackboxsw** [comment]
Thank you for vigilance here. I quick fired the issue an overlooked the call.
